name: deep_learning
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0=py37_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - bzip2=1.0.8=h0b31af3_2
  - ca-certificates=2020.1.1=0
  - cairo=1.16.0=h0ab9d94_1001
  - certifi=2019.11.28=py37_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.12=h90a0687_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - expat=2.2.6=h0a44026_0
  - ffmpeg=4.0=h01ea3c9_0
  - fontconfig=2.13.1=h1027ab8_1000
  - freetype=2.9.1=hb4e5f40_0
  - fribidi=1.0.5=h1de35cc_0
  - gettext=0.19.8.1=h15daf44_3
  - glib=2.63.1=hd977a24_0
  - graphite2=1.3.13=h2098e52_1000
  - graphviz=2.40.1=hefbbd9a_2
  - harfbuzz=1.8.8=hb8d4a28_0
  - hdf5=1.10.2=hc401514_3
  - icu=58.2=h4b95b61_1
  - importlib_metadata=1.3.0=py37_0
  - intel-openmp=2019.4=233
  - ipykernel=5.1.3=py37h39e3cac_0
  - ipython=7.11.1=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - jasper=2.0.14=h636a363_1
  - jedi=0.15.2=py37_0
  - jinja2=2.10.3=py_0
  - jpeg=9b=he5867d9_2
  - jsonschema=3.2.0=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=5.3.4=py37_0
  - jupyter_console=6.0.0=py37_0
  - jupyter_core=4.6.1=py37_0
  - kiwisolver=1.1.0=py37h0a44026_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libopencv=3.4.2=h7c891bd_1
  - libopus=1.3=h1de35cc_0
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.16=h3efe00b_0
  - libtiff=4.0.9=he6b73bb_1
  - libvpx=1.7.0=h378b8a2_0
  - libxml2=2.9.9=hf6e021a_1
  - markupsafe=1.1.1=py37h1de35cc_0
  - matplotlib=3.1.1=py37h54f8f79_0
  - mistune=0.8.4=py37h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.15=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - more-itertools=8.0.2=py_0
  - nb_conda_kernels=2.2.2=py37_0
  - nbconvert=5.6.1=py37_0
  - nbformat=4.4.0=py37_0
  - ncurses=6.1=h0a44026_1
  - notebook=6.0.2=py37_0
  - numpy=1.17.4=py37h890c691_0
  - numpy-base=1.17.4=py37h6575580_0
  - opencv=3.4.2=py37h6fd60c2_1
  - openssl=1.1.1d=h1de35cc_4
  - pandas=0.25.3=py37h0a44026_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - pango=1.42.4=h060686c_0
  - parso=0.5.2=py_0
  - pcre=8.43=h0a44026_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=19.3.1=py37_0
  - pixman=0.38.0=h01d97ff_1003
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py37_0
  - ptyprocess=0.6.0=py37_0
  - py-opencv=3.4.2=py37h7c891bd_1
  - pydotplus=2.0.2=py37_1
  - pygments=2.5.2=py_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py37h655552a_2
  - pyrsistent=0.15.6=py37h1de35cc_0
  - python=3.7.6=h359304d_2
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pyzmq=18.1.0=py37h0a44026_0
  - qt=5.9.7=h468cd18_1
  - qtconsole=4.6.0=py_1
  - readline=7.0=h1de35cc_5
  - send2trash=1.5.0=py37_0
  - setuptools=44.0.0=py37_0
  - sip=4.19.8=py37h0a44026_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1=ha441bb4_0
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.3=py37h1de35cc_0
  - traitlets=4.3.3=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - wheel=0.33.6=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - xz=5.2.4=h1de35cc_4
  - zeromq=4.3.1=h0a44026_3
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - absl-py==0.9.0
    - astor==0.8.1
    - cachetools==4.0.0
    - chardet==3.0.4
    - gast==0.2.2
    - google-auth==1.10.0
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.1.8
    - grpcio==1.26.0
    - h5py==2.10.0
    - idna==2.8
    - joblib==0.14.1
    - keras==2.3.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - markdown==3.1.1
    - oauthlib==3.1.0
    - opt-einsum==3.1.0
    - pillow==7.0.0
    - protobuf==3.11.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydot==1.4.1
    - pyyaml==5.3
    - requests==2.22.0
    - requests-oauthlib==1.3.0
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - tensorboard==2.1.0
    - tensorflow==2.1.0
    - tensorflow-estimator==2.1.0
    - termcolor==1.1.0
    - tqdm==4.43.0
    - urllib3==1.25.7
    - werkzeug==0.16.0
    - wrapt==1.11.2
prefix: /Users/moelgendy/anaconda3/envs/deep_learning

